apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../gotk
patches:
  - path: gotk-patches/helm-controller-certs-patch.yaml
  - path: gotk-patches/notification-controller-certs-patch.yaml
  - path: gotk-patches/source-controller-certs-patch.yaml
