apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          volumeMounts:
            - name: ca-certs
              mountPath: /etc/ssl/certs/Company-Root-CA.crt
              subPath: Company-Root-CA.crt
              readOnly: true
      volumes:
        - name: ca-certs
          configMap:
            defaultMode: 0600
            name: company-ca-certs