connectors:
- type: github
  id: github
  name: Github
  config:
    "clientID": "$GITHUB_CLIENT_ID"
    "clientSecret": "$GITHUB_CLIENT_SECRET"
    teamNameField: slug
    useLoginAsID: true
    orgs:
    - name: $GITHUB_AUTH_ORG
      teams:
      - admin
    "baseURL": "https://github.com"
    "groups":
    - "$GITHUB_AUTH_ORG"
    "redirectURI": "https://dex.${local_dns}/callback"
"issuer": "https://dex.${local_dns}"
"oauth2":
  "skipApprovalScreen": true
"staticClients":
- "id": "vault"
  "name": "Vault"
  "redirectURIs":
  - "https://vault.${local_dns}/ui/vault/auth/oidc/oidc/callback"
  "secret": $VAULT_DEX_CLIENT_SECRET
"storage":
  "type": "memory"
"web":
  "http": "0.0.0.0:5556"