apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  chart:
    spec:
      chart: metrics-server
      version: 3.12.2
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
  interval: 10m0s
  timeout: 5m
  values:
    apiService:
      insecureSkipTLSVerify: true
    tls:
      type: helm
      clusterDomain: kubernetes.docker.internal
  postRenderers:
    - kustomize:
        patches:
        - target:
            kind: Deployment
            name: metrics-server
          patch: |-
            - op: add
              path: /spec/template/spec/hostAliases
              value:
                - ip: ${clusterIP}
                  hostnames:
                  - "dex.${dnsSuffix}"
                  - "vault.${dnsSuffix}"

            - op: add
              path: /spec/template/spec/volumes/-
              value:
                name: local-ca
                configMap:
                  name: local-ca

            - op: add
              path: /spec/template/spec/containers/0/volumeMounts/-
              value:
                name: local-ca
                mountPath: /etc/ssl/certs/local-ca.pem
                subPath: CA.cer
                readOnly: false
