apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  chart:
    spec:
      chart: harbor
      version: v1.16.3
      sourceRef:
        kind: HelmRepository
        name: harbor
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
  interval: 10m0s
  timeout: 5m
  values:
    externalURL: https://harbor.${dnsSuffix}
    existingSecretAdminPassword: admin-password
    existingSecretAdminPasswordKey: adminPasswd

    expose:
      ingress:
        hosts:
          core: harbor.${dnsSuffix}
        className: nginx
